### ISSUE TITLE
Readme.md contains reference to old/wrong/future code:   PeppolValidation.initThirdParty (aVESRegistry); 

### ISSUE THREAD

**Issue by kukel** [phax/phive#15]
The line referencing

`PeppolValidation.initThirdParty (aVESRegistry);`

is wrong. Not sure what it should be. All other ones (the 'third party ones like SimplerInvoicing etc) explitictly or a PeppolLegacyThirdParty or....

**Comment by phax** [comment]
Thanks for pointing that out. The description of the respective sub-modules should be inside phive-rules and not here
