### ISSUE TITLE
Default or expose a method to use latest versions of rules

### ISSUE THREAD

**Issue by adammscisz** [phax/phive#16]
Currently when new rules appear, one needs to change both: update *-rules dependency and and pass specific VESID ruleset to Registry.

It would be nice to have an option to use latest ruleset by default so that pom update is enough to be up to date with changes.

**Comment by phax** [comment]
Finally the pseudo version `latest` can be used to resolve the latest version via `ValidationExecutorSetRegistry.getByID`. Alternatively `ValidationExecutorSetRegistry.getLatestVersion` can be used to manually determine the latest version.

This is part of the 8.0.1 release.
