### ISSUE TITLE
Failed to create JAXB context for packages 'com.helger.schematron.svrl.jaxb'

### ISSUE THREAD

**Issue by Berny1987a** [phax/phive#21]
Dear Mr.Helger, 

I am trying to include the phive-master and phive-rules-master within my Maven project. I am not a native Java developer therefore I find some errors quite difficult to understand and I do apologize in advance for my Java-related ignorance :(

I created a local Java project in IntelliJ (new version downloaded 12/2023).  Installed JAVA on my MacOS is:

java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)

I converted my Java project into Maven project and added dependencies into POM.xml file

   <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.9</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>com.helger.phive</groupId>
      <artifactId>phive-xml</artifactId>
      <version>9.0.1-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.helger.phive.rules</groupId>
      <artifactId>phive-rules-en16931</artifactId>
      <version>3.1.7-SNAPSHOT</version>
    </dependency>

Additionally, I added required modules into module-info.java:

    requires com.helger.phive.xml;
    requires com.helger.diver.api;
    requires com.helger.phive.api;
    requires com.helger.phive.en16931;
    requires java.xml;
    requires com.helger.xml;
    requires com.helger.commons;

My main code looks like this:

...

import com.helger.commons.io.resource.ClassPathResource;
import com.helger.diver.api.version.VESID;
import com.helger.phive.api.execute.ValidationExecutionManager;
import com.helger.phive.api.executorset.IValidationExecutorSet;
import com.helger.phive.api.executorset.ValidationExecutorSet;
import com.helger.phive.api.executorset.ValidationExecutorSetRegistry;
import com.helger.phive.api.result.ValidationResultList;
import com.helger.phive.en16931.EN16931Validation;
import com.helger.phive.xml.source.IValidationSourceXML;
import com.helger.phive.xml.source.ValidationSourceXML;
import com.helger.phive.xml.xsd.ValidationExecutorXSD;
import com.helger.xml.XMLHelper;
import org.w3c.dom.Document;
import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.IOException;
import java.io.InputStream;
import java.io.StringReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Locale;

...

 final ValidationExecutorSetRegistry<IValidationSourceXML> aRegistry = new ValidationExecutorSetRegistry <> ();
 EN16931Validation.initEN16931(aRegistry);

VESID aVESID = EN16931Validation.VID_UBL_INVOICE_1311;
ValidationResultList aValidationResult = null;

 final IValidationExecutorSet<IValidationSourceXML> aVES = aRegistry.getOfID (aVESID);
 
if (aVES != null) {

            //creating document node class from input string (invoice xml example)
           // content - string variable - read xml from file
            Document doc = convertStringToXMLDocument(content);

            final IValidationSourceXML aSource = ValidationSourceXML.create(null, XMLHelper.getOwnerDocument(doc));
            aValidationResult = ValidationExecutionManager.executeValidation (aVES, aSource);

}

-------------------------------------------------------------------------
The aValidationResult is a list that has 2 elements. The first one is SUCCESS = TRUE, the second element has an error:

"Failed to create JAXB context for packages 'com.helger.schematron.svrl.jaxb' using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@214c265e"

The error is somewhere in the GenericJAXBMarshaller.java file, method called: "getJAXBContext" (package com.helger.jaxb) on line 482

<img width="1470" alt="Screenshot 2023-12-31 at 20 15 59" src="https://github.com/phax/phive/assets/150153612/28684b94-35a6-4447-a0fa-1934101b76d1">

Maybe JAXB is obsolete, maybe I have the wrong version of Java, maybe there should be some alternative implementation using JAKARTA maven packages? 

Please could you help me with some ideas? I have a feeling that this is the only thing that's preventing me from fully executing the validation process.

Regards

Bernard

**Comment by phax** [comment]
Please make sure, that this dependency is also in your pom.xml (it's the JAXB implementation):
```xml
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>4.0.4</version>
    </dependency>
```

Maybe you need to add something to the module-info - I don't know.
hth

**Comment by phax** [comment]
@Berny1987a  did that resolve your issue?

**Comment by Berny1987a** [comment]
Hi,

Hard to say. I tried milion of combinations of maven dependencies, and at the end I managed to get it to work. Why? How? I dont't know. :D 

This is the list of dependencies that I use in my POM file:

<dependencies>
    <dependency>
        <groupId>org.glassfish.jersey.core</groupId>
        <artifactId>jersey-server</artifactId>
        <version>3.1.5</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.jersey.containers</groupId>
        <artifactId>jersey-container-servlet</artifactId>
        <version>3.1.5</version>
    </dependency>

<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>3.1.5</version>
</dependency>

    <dependency>
	    <groupId>jakarta.platform</groupId>
	    <artifactId>jakarta.jakartaee-api</artifactId>
	    <version>9.1.0</version>
	    <scope>provided</scope>
	</dependency>
	

 <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>2.0.9</version>
      <scope>runtime</scope>
    </dependency>


      <dependency>
          <groupId>com.helger.commons</groupId>
          <artifactId>ph-json</artifactId>
          <version>11.1.3</version>
      </dependency>
      <dependency>
          <groupId>com.helger.phive</groupId>
          <artifactId>phive-result</artifactId>
          <version>9.0.1-SNAPSHOT</version>
      </dependency>
    <dependency>
      <groupId>com.helger.phive</groupId>
      <artifactId>phive-xml</artifactId>
      <version>9.0.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.helger.phive.rules</groupId>
      <artifactId>phive-rules-en16931</artifactId>
      <version>3.1.7-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>4.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.helger.commons</groupId>
      <artifactId>ph-jaxb</artifactId>
      <version>11.1.3</version>
    </dependency>
    <dependency>
      <groupId>com.helger.commons</groupId>
      <artifactId>ph-jaxb-adapter</artifactId>
      <version>11.1.0</version>
    </dependency>
  </dependencies>

Thanks once more for your support. All the best in the new 2024. 

Regards 

Berny

**Comment by phax** [comment]
Great :)
Just a recommendation: always stick with release versions and never use `SNAPSHOT` versions, as they can change - they are "in development" versions.

So please use this instead:
```xml
 <dependency>
      <groupId>com.helger.phive</groupId>
      <artifactId>phive-result</artifactId>
      <version>9.0.0</version>  <!--- CHANGE -->
  </dependency>
<dependency>
  <groupId>com.helger.phive</groupId>
  <artifactId>phive-xml</artifactId>
  <version>9.0.0</version>  <!--- CHANGE -->
</dependency>
<dependency>
  <groupId>com.helger.phive.rules</groupId>
  <artifactId>phive-rules-en16931</artifactId>
  <version>3.1.6</version>  <!--- CHANGE -->
</dependency>
<dependency>
  <groupId>com.sun.xml.ws</groupId>
  <artifactId>jaxws-rt</artifactId>
  <version>4.0.2</version>  <!--- CHANGE -->
</dependency>
<dependency>
  <groupId>com.helger.commons</groupId>
  <artifactId>ph-jaxb</artifactId>
  <version>11.1.3</version>
</dependency>
<dependency>
  <groupId>com.helger.commons</groupId>
  <artifactId>ph-jaxb-adapter</artifactId>
  <version>11.1.3</version> <!--- CHANGE -->
</dependency>
```
