### ISSUE TITLE
detect document type

### ISSUE THREAD

**Issue by schmitch** [phax/phive#25]
is there a way to automatically detect the type of the invoice and do a validation? 
at the moment I also could not find any example for that.

**Comment by phax** [comment]
Yes sure. Please look at https://github.com/phax/ddd :)

**Comment by schmitch** [comment]
oh thanks, I will close the issue ! 👍

**Comment by schmitch** [comment]
@phax I do not want to create a new issue so I try it here.
I tested the validator and I always get failures:

```
                    result.getAllFailures().forEach(error -> {
                        System.out.println("Failure: " + error.getErrorID() + " = " + error.getAsString(Locale.GERMAN));
                    });
```

will print for an XRechnung UBL Invoice 3.0.2:

```
Failure: null = [warn] Transformationswarnung (net.sf.saxon.trans.XPathException: A function that computes atomic values should use xsl:sequence rather than xsl:value-of)
Failure: null = [warn] Transformationswarnung (net.sf.saxon.trans.XPathException: A function that computes atomic values should use xsl:sequence rather than xsl:value-of)
```

is there a way to disable that warning? 
also what is the difference between failure and error? does he still validate the ubl business rules if there is an xpathexception?

**Comment by schmitch** [comment]
hm okai. well I tought I could just do the following, to know if a document is valid:
`result.containsNoError() && result.containsNoFailure()`

however I guess its more of:

```java
        var errorList = Stream.of(result.getAllErrors(), result.getAllFailures())
                .flatMap(Collection::stream)
                .toList();
        var warnings = errorList.stream().filter(e -> e.hasErrorLevel(EErrorLevel.WARN)).toList();
        var errors = errorList.stream().filter(e -> e.hasErrorLevel(EErrorLevel.ERROR) || e.hasErrorLevel(EErrorLevel.FATAL_ERROR)).toList();
        var success = errors.isEmpty();

```

**Comment by phax** [comment]
Btw. `result.getAllFailures()` is a true subset of `getAllErrors()` - so you can work on that only
Additionally the `IErrorLevel` interface has some nice helper methods so that you can run it like this:
```java
var errorList = result.getAllErrors();
var warnings = errorList.stream().filter(e -> e.hasErrorLevel(EErrorLevel.WARN)).toList();
var errors = errorList.stream().filter(e -> e.isGE(EErrorLevel.ERROR)).toList();
var success =errorList.stream().filter(e -> e.isLT(EErrorLevel.WARN)).toList();
```
